import { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import * as webllm from '@mlc-ai/web-llm';
import { Activity, ArrowUpRight, Bot, Brain, CandlestickChart, CheckCircle2, CircleStop, Copy, Download, Gauge, Menu, Moon, Pause, Play, Plus, RefreshCw, Search, Settings, ShieldCheck, Sun, Target, TrendingDown, TrendingUp, Wifi, WifiOff, X, Zap } from 'lucide-react';
import './styles.css';
import { classifyFinancialHeadline, getFinBert } from './news-nlp';

type Role='user'|'assistant';
type Msg={id:string;role:Role;content:string;createdAt:number;error?:boolean};
type Chat={id:string;title:string;messages:Msg[];updatedAt:number};
type Candle={time:number;open:number;high:number;low:number;close:number;volume:number;closed:boolean};
type SettingsState={temperature:number;maxTokens:number;saveChats:boolean;theme:'dark'|'light'};
type NewsItem={title:string;url:string;source:string;publishedAt:string;sentiment:'positive'|'negative'|'neutral';score:number;summary:string};

const MODEL='Llama-3.2-1B-Instruct-q4f16_1-MLC';
const STORE='open-trading-ai.v14';
const SETTINGS_KEY=`${STORE}.settings`;
const CHATS_KEY=`${STORE}.chats`;
const SYMBOLS=[{label:'BTC/USDT',symbol:'btcusdt'},{label:'ETH/USDT',symbol:'ethusdt'},{label:'SOL/USDT',symbol:'solusdt'},{label:'BNB/USDT',symbol:'bnbusdt'}];
const INTERVALS=['1m','5m','15m','1h'];
const DEFAULT_SETTINGS:SettingsState={temperature:0.2,maxTokens:1600,saveChats:true,theme:'dark'};
const SYSTEM=`You are Open Trading AI V13, a day-trading-focused educational assistant. Analyze only the market context provided to you. You may discuss intraday technical analysis, price action, market structure, momentum, volatility, liquidity concepts, indicators, risk management, strategy rules, backtesting and trade journaling. Never invent live prices, candles, volume, news or indicators. Treat news headlines as evidence from a public feed, not as verified truth. Always preserve source and timestamp when referencing news. When live data is provided, cite the symbol, timeframe and timestamp from the context. Distinguish observed data from inference. Never claim certainty, guaranteed profit or privileged information. Do not place orders. Prefer explicit assumptions, invalidation, risk limits and no-trade conditions. This is educational information, not personalized financial advice.`;
const STARTERS=[
 ['Market snapshot','Analyze the current live market context. Summarize trend, momentum, volatility, key levels and the highest-quality no-trade conditions.'],
 ['Day trade setup','Using the current live candles and indicators, construct one rules-based day-trading scenario with entry trigger, invalidation, target logic and R:R.'],
 ['Risk check','Evaluate the setup from a risk-management perspective. Explain position sizing inputs and what would invalidate the trade before entry.'],
 ['Scalp plan','Build a short-term plan for the current timeframe using price action plus EMA, RSI and volume, and state what would keep me out of the market.'],
];

function uid(){return `${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function load<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
function save(key:string,val:unknown){try{localStorage.setItem(key,JSON.stringify(val))}catch{}}
function escapeHtml(s:string){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function md(text:string){return escapeHtml(text).split('```').map((part,i)=>i%2?<pre key={i}><code>{part.trim()}</code></pre>:<span key={i}>{part.split(/(\*\*.*?\*\*|`[^`]+`)/g).map((x,j)=>x.startsWith('**')?<strong key={j}>{x.slice(2,-2)}</strong>:x.startsWith('`')?<code className="inline-code" key={j}>{x.slice(1,-1)}</code>:<span key={j}>{x.split('\n').map((l,k)=><span key={k}>{k>0&&<br/>}{l}</span>)}</span>)}</span>)}
function fmt(n:number){return new Intl.NumberFormat('en-US',{maximumFractionDigits:n>=100?2:4}).format(n)}
function download(name:string,data:string,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
function ema(values:number[],period:number){if(!values.length)return 0;const k=2/(period+1);let e=values[0];for(let i=1;i<values.length;i++)e=values[i]*k+e*(1-k);return e}
function rsi(values:number[],period=14){if(values.length<period+1)return 50;let gains=0,losses=0;for(let i=1;i<=period;i++){const d=values[i]-values[i-1];if(d>=0)gains+=d;else losses-=d}let ag=gains/period,al=losses/period;for(let i=period+1;i<values.length;i++){const d=values[i]-values[i-1];ag=(ag*(period-1)+Math.max(d,0))/period;al=(al*(period-1)+Math.max(-d,0))/period}if(al===0)return 100;return 100-(100/(1+ag/al))}
function volumeSma(c:Candle[],period=20){const s=c.slice(-period).map(x=>x.volume);return s.length?s.reduce((a,b)=>a+b,0)/s.length:0}
function stats(c:Candle[]){const closes=c.map(x=>x.close);const last=closes.at(-1)??0;return {price:last,ema9:ema(closes,9),ema21:ema(closes,21),rsi:rsi(closes,14),vol:c.at(-1)?.volume??0,volSma:volumeSma(c),high:Math.max(...c.map(x=>x.high)),low:Math.min(...c.map(x=>x.low))}}
function candleFromRow(r:any[]):Candle{return {time:Number(r[0]),open:Number(r[1]),high:Number(r[2]),low:Number(r[3]),close:Number(r[4]),volume:Number(r[5]),closed:true}}

function App(){
 const [settings,setSettings]=useState<SettingsState>(()=>({...DEFAULT_SETTINGS,...load(SETTINGS_KEY,DEFAULT_SETTINGS)}));
 const [chats,setChats]=useState<Chat[]>(()=>settings.saveChats?load(CHATS_KEY,[]):[]);
 const [activeId,setActiveId]=useState<string|null>(()=>settings.saveChats?load<Chat[]>(CHATS_KEY,[])[0]?.id??null:null);
 const [activeSymbol,setActiveSymbol]=useState('btcusdt'); const [timeframe,setTimeframe]=useState('5m');
 const [news,setNews]=useState<NewsItem[]>([]); const [newsLoading,setNewsLoading]=useState(false); const [newsError,setNewsError]=useState<string|null>(null); const [newsUpdated,setNewsUpdated]=useState<number|null>(null);
 const [live,setLive]=useState(true); const [connected,setConnected]=useState(false); const [candles,setCandles]=useState<Candle[]>([]); const [marketError,setMarketError]=useState<string|null>(null); const [lastTick,setLastTick]=useState<number|null>(null);
 const [input,setInput]=useState(''); const [generating,setGenerating]=useState(false); const [loading,setLoading]=useState(false); const [progress,setProgress]=useState(0); const [status,setStatus]=useState('Ready');
 const [sidebar,setSidebar]=useState(true); const [settingsOpen,setSettingsOpen]=useState(false); const [query,setQuery]=useState(''); const [webgpu,setWebgpu]=useState(false);
 const engine=useRef<webllm.MLCEngineInterface|null>(null); const requestId=useRef<string|null>(null); const ws=useRef<WebSocket|null>(null); const abortRef=useRef(false); const bottom=useRef<HTMLDivElement>(null); const inputRef=useRef<HTMLTextAreaElement>(null);
 const active=chats.find(c=>c.id===activeId)??null; const messages=active?.messages??[];
 const info=useMemo(()=>stats(candles),[candles]);
 const visibleChats=useMemo(()=>{const q=query.toLowerCase().trim();return [...chats].filter(c=>!q||c.title.toLowerCase().includes(q)||c.messages.some(m=>m.content.toLowerCase().includes(q))).sort((a,b)=>b.updatedAt-a.updatedAt)},[chats,query]);
 const delta=useMemo(()=>candles.length>1?((info.price-(candles.at(-2)?.close??info.price))/(candles.at(-2)?.close??info.price))*100:0,[candles,info.price]);
 const assetQuery=()=>{const m=SYMBOLS.find(s=>s.symbol===activeSymbol)?.label.split('/')[0]??activeSymbol.toUpperCase(); const map:Record<string,string>={BTC:'Bitcoin OR BTC OR cryptocurrency',ETH:'Ethereum OR ETH OR cryptocurrency',SOL:'Solana OR SOL OR cryptocurrency',BNB:'Binance OR BNB OR cryptocurrency'}; return map[m]??m};
 const fetchNews=async()=>{setNewsLoading(true);setNewsError(null);try{const q=encodeURIComponent(`(${assetQuery()}) (crypto OR blockchain OR markets OR ETF OR regulation OR exchange)`);const url=`https://api.gdeltproject.org/api/v2/doc/doc?query=${q}&mode=artlist&format=json&maxrecords=12&timespan=6h&sort=datedesc`;const r=await fetch(url);if(!r.ok)throw new Error(`News request failed (${r.status})`);const data=await r.json();const arr:Array<any>=Array.isArray(data?.articles)?data.articles:Array.isArray(data)?data:[];
 const base=arr.map((a:any)=>({title:String(a.title??'').trim(),url:String(a.url??'#'),source:String(a.domain??a.sourcecountry??'GDELT'),publishedAt:String(a.seendate??new Date().toISOString()),summary:String(a.snippet??'').replace(/\s+/g,' ').trim()})).filter((x:any)=>x.title).slice(0,10);
 setStatus('Loading financial NLP'); setProgress(0);
 try { await getFinBert((p,t)=>{setProgress(p);setStatus(`FinBERT: ${t}`)}); } catch { throw new Error('Financial NLP could not start. WebGPU is required for browser-side sentiment analysis.'); }
 const analyzed: NewsItem[]=[]; for(const item of base){ try { const r=await classifyFinancialHeadline(`${item.title}. ${item.summary}`.trim()); analyzed.push({...item,...r}); } catch { analyzed.push({...item,sentiment:'neutral',score:0}); } }
 setNews(analyzed);setNewsUpdated(Date.now());setProgress(0);setStatus('Ready');if(!analyzed.length)setNewsError('Keine passenden News im letzten 6-Stunden-Fenster gefunden.')}catch(e){setNewsError(e instanceof Error?e.message:'News feed unavailable');setNews([]);setProgress(0);setStatus('Ready')}finally{setNewsLoading(false)}};
 const newsContext=()=>news.length?`LIVE NEWS CONTEXT\nFeed: GDELT public news search\n${news.slice(0,8).map((n,i)=>`${i+1}. ${n.title} | source=${n.source} | published=${n.publishedAt} | sentiment=${n.sentiment} | url=${n.url}`).join('\n')}`:'LIVE NEWS CONTEXT\nNo verified news items are currently available. Do not invent news.';

 const context=()=>`LIVE MARKET CONTEXT\\nExchange: Binance public market data\\nSymbol: ${activeSymbol.toUpperCase()}\\nTimeframe: ${timeframe}\\nLast price: ${info.price}\\nEMA9: ${info.ema9}\\nEMA21: ${info.ema21}\\nRSI14: ${info.rsi}\\nLast volume: ${info.vol}\\n20-candle average volume: ${info.volSma}\\nVisible high: ${info.high}\\nVisible low: ${info.low}\\nLast update: ${lastTick?new Date(lastTick).toISOString():'unknown'}\\nChange vs previous candle close: ${delta.toFixed(3)}%\\nThe feed is public market data only. No account/order data is available. Treat the current candle as provisional until it closes.`;

 useEffect(()=>{document.documentElement.dataset.theme=settings.theme;save(SETTINGS_KEY,settings)},[settings]);
 useEffect(()=>{if(settings.saveChats)save(CHATS_KEY,chats.slice(0,100)); else localStorage.removeItem(CHATS_KEY)},[chats,settings.saveChats]);
 useEffect(()=>{setWebgpu(Boolean('gpu' in navigator&&window.isSecureContext))},[]);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:generating?'auto':'smooth'}),[messages.length,generating]);
 useEffect(()=>{function key(e:KeyboardEvent){const m=e.ctrlKey||e.metaKey;if(m&&e.key.toLowerCase()==='n'){e.preventDefault();newChat()}if(m&&e.key.toLowerCase()==='k'){e.preventDefault();inputRef.current?.focus()}if(e.key==='Escape'){stop();setSettingsOpen(false)}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 useEffect(()=>{fetchNews(); const id=window.setInterval(fetchNews, 180000); return()=>window.clearInterval(id)},[activeSymbol]);
 useEffect(()=>{if(!live)return; let closed=false; setMarketError(null); setConnected(false); setCandles([]);
   (async()=>{try{const r=await fetch(`https://api.binance.com/api/v3/klines?symbol=${activeSymbol.toUpperCase()}&interval=${timeframe}&limit=120`); if(!r.ok)throw new Error(`History request failed (${r.status})`); const data=await r.json(); if(!closed)setCandles(data.map(candleFromRow));}catch(e){if(!closed)setMarketError(e instanceof Error?e.message:'Unable to load market history')}})();
   const url=`wss://stream.binance.com:9443/ws/${activeSymbol}@kline_${timeframe}`; let socket:WebSocket|null=null;
   try{socket=new WebSocket(url);ws.current=socket;socket.onopen=()=>{if(!closed)setConnected(true)};socket.onerror=()=>{if(!closed){setConnected(false);setMarketError('Live websocket connection failed')}};socket.onclose=()=>{if(!closed)setConnected(false)};socket.onmessage=(ev)=>{try{const p=JSON.parse(ev.data);const k=p.k;const next:Candle={time:Number(k.t),open:Number(k.o),high:Number(k.h),low:Number(k.l),close:Number(k.c),volume:Number(k.v),closed:Boolean(k.x)};setCandles(cs=>{const copy=[...cs];const idx=copy.findIndex(x=>x.time===next.time);if(idx>=0)copy[idx]=next;else copy.push(next);return copy.slice(-160)});setLastTick(Date.now())}catch{}}}catch{setMarketError('Your browser cannot open the live market stream')}
   return()=>{closed=true;socket?.close();ws.current=null};
 },[activeSymbol,timeframe,live]);

 function patch(id:string,fn:(c:Chat)=>Chat){setChats(cs=>cs.map(c=>c.id===id?fn(c):c))}
 function newChat(){stop();const c:Chat={id:uid(),title:'New day-trading chat',messages:[],updatedAt:Date.now()};setChats(cs=>[c,...cs]);setActiveId(c.id);setInput('');requestAnimationFrame(()=>inputRef.current?.focus())}
 function stop(){abortRef.current=true;requestId.current=null;setGenerating(false);setLoading(false);setProgress(0);setStatus('Ready');try{engine.current?.interruptGenerate()}catch{}}
 async function ensureModel(){if(engine.current)return engine.current;if(!webgpu)throw new Error('WebGPU ist in diesem Browser/Context nicht verfügbar. Nutze einen aktuellen Browser über HTTPS oder localhost.');setLoading(true);setProgress(1);setStatus('Loading local model');try{const e=await webllm.CreateMLCEngine(MODEL,{initProgressCallback:p=>{setProgress(Math.round((p.progress??0)*100));setStatus(p.text||'Loading model')}});engine.current=e;setStatus('Model ready');return e}finally{setLoading(false)}}
 async function send(text=input.trim()){
  if(!text||generating)return;setInput('');setGenerating(true);abortRef.current=false;const rid=uid();requestId.current=rid;setStatus('Analyzing live market context');let cid=activeId;
  if(!cid){const c:Chat={id:uid(),title:text.replace(/\s+/g,' ').slice(0,52)||'Day-trading chat',messages:[],updatedAt:Date.now()};setChats(cs=>[c,...cs]);setActiveId(c.id);cid=c.id}
  const user:Msg={id:uid(),role:'user',content:text,createdAt:Date.now()};patch(cid,c=>({...c,title:c.messages.length?c.title:user.content.replace(/\s+/g,' ').slice(0,52)||'Day-trading chat',messages:[...c.messages,user],updatedAt:Date.now()}));
  const placeholder:Msg={id:uid(),role:'assistant',content:'',createdAt:Date.now()};patch(cid,c=>({...c,messages:[...c.messages,placeholder],updatedAt:Date.now()}));
  try{const e=await ensureModel();const target=chats.find(c=>c.id===cid);const history=[...(target?.messages??[]),user].slice(-16).map(m=>({role:m.role,content:m.content} as const));const liveContext=`${context()}\n\n${newsContext()}`;const req=await e.chat.completions.create({messages:[{role:'system',content:SYSTEM},{role:'user',content:`${liveContext}\\n\\nTrader request:\\n${text}`},...history],temperature:settings.temperature,max_tokens:settings.maxTokens,stream:true});let acc='';for await(const chunk of req){if(requestId.current!==rid||abortRef.current)break;const piece=chunk.choices?.[0]?.delta?.content??'';if(piece){acc+=piece;patch(cid,c=>({...c,messages:c.messages.map(m=>m.id===placeholder.id?{...m,content:acc}:m),updatedAt:Date.now()}))}} if(requestId.current===rid&&!abortRef.current&&acc==='')throw new Error('The model returned no text');
  }catch(e){const msg=e instanceof Error?e.message:'AI request failed';patch(cid,c=>({...c,messages:c.messages.map(m=>m.id===placeholder.id?{...m,content:msg,error:true}:m),updatedAt:Date.now()}));setStatus('Error');setMarketError(msg)}finally{if(requestId.current===rid){requestId.current=null;setGenerating(false);setStatus('Ready')}}
 }
 function regenerate(){if(!active||generating)return;const lastUser=[...active.messages].reverse().find(m=>m.role==='user');if(!lastUser)return;patch(active.id,c=>({...c,messages:c.messages.slice(0,-1),updatedAt:Date.now()}));void send(lastUser.content)}
 function copy(text:string){navigator.clipboard?.writeText(text)}
 function exportChat(){if(!active)return;download(`${active.title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'chat'}.md`,active.messages.map(m=>`## ${m.role==='user'?'Trader':'Open Trading AI'}\\n\\n${m.content}`).join('\\n\\n'))}
 function clearChat(){if(activeId)patch(activeId,c=>({...c,messages:[],updatedAt:Date.now()}))}
 const symbolInfo=SYMBOLS.find(s=>s.symbol===activeSymbol)!;
 return <div className="app"><aside className={`sidebar ${sidebar?'open':''}`}><div className="brand"><div className="brand-mark"><TrendingUp size={17}/></div><div><strong>Open Trading AI</strong><span>Day Trading V12</span></div></div><button className="new-btn" onClick={newChat}><Plus size={15}/>New chat</button><div className="searchbox"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search chats"/></div><div className="side-label">CHATS</div><div className="chat-list">{visibleChats.map(c=><button className={`chat-link ${c.id===activeId?'active':''}`} key={c.id} onClick={()=>setActiveId(c.id)}><Bot size={14}/><span>{c.title}</span></button>)}{!visibleChats.length&&<div className="side-empty">No chats yet.</div>}</div><div className="sidebar-footer"><div className="feed-chip"><span className={`dot ${connected?'live':''}`}/><div><strong>{connected?'LIVE FEED':'Feed offline'}</strong><small>Binance public market data</small></div></div><button className="side-settings" onClick={()=>setSettingsOpen(true)}><Settings size={14}/>Settings</button></div></aside>
 <main className="main"><header className="topbar"><button className="icon-btn" onClick={()=>setSidebar(v=>!v)}><Menu size={17}/></button><div className="ticker"><CandlestickChart size={15}/><strong>{symbolInfo.label}</strong><span className={delta>=0?'positive':'negative'}>{delta>=0?'+':''}{delta.toFixed(2)}%</span></div><div className="top-actions"><div className="live-status"><span className={`dot ${connected?'live':''}`}/>{connected?'LIVE':'OFFLINE'}</div><button className="icon-btn" onClick={()=>setSettingsOpen(true)}><Settings size={16}/></button><button className="icon-btn" onClick={()=>setSettings(s=>({...s,theme:s.theme==='dark'?'light':'dark'}))}>{settings.theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}</button></div></header>
 <section className="controls"><div className="select-row">{SYMBOLS.map(s=><button key={s.symbol} className={activeSymbol===s.symbol?'chip active':'chip'} onClick={()=>setActiveSymbol(s.symbol)}>{s.label}</button>)}</div><div className="select-row">{INTERVALS.map(t=><button key={t} className={timeframe===t?'chip active':'chip'} onClick={()=>setTimeframe(t)}>{t}</button>)}</div><button className={`live-btn ${live?'on':''}`} onClick={()=>setLive(v=>!v)}>{live?<Wifi size={14}/>:<WifiOff size={14}/>} {live?'Live market':'Demo mode'}</button></section>
 <section className="dashboard"><div className="card chart-card"><div className="card-head"><div><span className="eyebrow">LIVE MARKET</span><h2>{symbolInfo.label} · {timeframe}</h2></div><div className="price"><strong>{fmt(info.price)}</strong><span className={delta>=0?'positive':'negative'}>{delta>=0?'+':''}{delta.toFixed(2)}%</span></div></div>{marketError&&<div className="error-bar">{marketError}</div>}<Chart candles={candles}/><div className="stats"><Metric label="EMA 9" value={fmt(info.ema9)} tone={info.price>=info.ema9?'positive':'negative'}/><Metric label="EMA 21" value={fmt(info.ema21)} tone={info.price>=info.ema21?'positive':'negative'}/><Metric label="RSI 14" value={info.rsi.toFixed(1)} tone={info.rsi>70?'negative':info.rsi<30?'positive':''}/><Metric label="Volume" value={`${info.volSma?((info.vol/info.volSma)*100).toFixed(0):'0'}% avg`} /></div><div className="feed-meta"><span><CircleStop size={11}/> public feed</span><span>{lastTick?`updated ${new Date(lastTick).toLocaleTimeString()}`:'waiting for tick'}</span><span>current candle may be provisional</span></div></div>
 <aside className="rightcol"><div className="card news-card"><div className="card-head compact"><div><span className="eyebrow">LIVE NEWS · FINBERT</span><h3>Market headlines</h3></div><button className="icon-btn" onClick={fetchNews} disabled={newsLoading}><RefreshCw size={14}/></button></div><div className="news-meta"><span className={newsError?'negative':'positive'}>{newsLoading?'Updating…':newsError?'Feed issue':'Live feed'}</span><span>{newsUpdated?`updated ${new Date(newsUpdated).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'not loaded'}</span></div><div className="news-list">{news.slice(0,6).map(n=><a className="news-item" href={n.url} target="_blank" rel="noreferrer" key={`${n.url}-${n.publishedAt}`}><div><strong>{n.title}</strong><span>{n.source} · {n.publishedAt.slice(0,16).replace('T',' ')}</span></div><b className={n.sentiment}>{n.sentiment} · {(n.score*100).toFixed(0)}%</b></a>)}{!news.length&&!newsLoading&&<div className="news-empty">{newsError||'Keine News verfügbar.'}</div>}</div><div className="small-note"><ShieldCheck size={12}/> Headlines use local FinBERT financial NLP. Confidence is model output, not truth; source links and timestamps are shown.</div></div><div className="card"><div className="card-head compact"><div><span className="eyebrow">AI SIGNAL CONTEXT</span><h3>Market state</h3></div><Brain size={17}/></div><div className="state-grid"><Metric label="Trend" value={info.price>=info.ema21?'Bullish':'Bearish'} tone={info.price>=info.ema21?'positive':'negative'}/><Metric label="Momentum" value={info.rsi>=50?'Positive':'Negative'} tone={info.rsi>=50?'positive':'negative'}/><Metric label="Volume" value={info.vol>=info.volSma?'Above avg':'Below avg'}/><Metric label="Range" value={`${fmt(info.high-info.low)}`}/></div><div className="small-note"><ShieldCheck size={12}/> AI only receives the latest live context; it does not have your account or order access.</div></div><div className="card"><div className="card-title"><Target size={14}/>Risk calculator</div><RiskCalc price={info.price}/></div><div className="card"><div className="card-title"><Zap size={14}/>Quick actions</div><div className="quick-actions"><button onClick={()=>send(STARTERS[0][1])}>Analyze market</button><button onClick={()=>send(STARTERS[1][1])}>Build setup</button><button onClick={()=>send(STARTERS[2][1])}>Risk check</button></div></div></aside></section>
 <section className="chat-shell"><div className="chat-head"><div><span className="eyebrow">LOCAL AI DESK</span><h2>{active?.title??'Live day-trading assistant'}</h2></div><div className="chat-tools"><button onClick={clearChat} disabled={!active}><X size={13}/>Clear</button><button onClick={exportChat} disabled={!active}><Download size={13}/>Export</button></div></div><div className="chat-area">{!messages.length?<div className="welcome"><div className="hero"><Brain size={25}/></div><h1>Analyze the market.<br/><span>Stay systematic.</span></h1><p>V13 combines a local browser model with live market data and a public news feed. No order execution, no account access.</p><div className="starter-grid">{STARTERS.map(([t,s])=><button key={t} onClick={()=>send(s)}><strong>{t}</strong><span>{s}</span></button>)}</div>{loading&&<Loader progress={progress} status={status}/>}</div>:<div className="messages">{messages.map(m=><div className="message" key={m.id}><div className={`avatar ${m.role}`}>{m.role==='user'?'YOU':'AI'}</div><div className="message-main"><div className="message-meta"><strong>{m.role==='user'?'Trader':'Open Trading AI'}</strong><span>{new Date(m.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span></div><div className={`bubble ${m.error?'error':''}`}>{m.content?md(m.content):generating?<span className="typing"><i/><i/><i/></span>:null}</div>{m.role==='assistant'&&m.content&&<div className="message-actions"><button onClick={()=>copy(m.content)}><Copy size={12}/>Copy</button><button onClick={regenerate}><RefreshCw size={12}/>Regenerate</button></div>}</div></div>)}<div ref={bottom}/></div>}</div><div className="composer-wrap"><div className="composer"><textarea ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();generating?stop():void send()}}} placeholder="Ask about this live market, a setup, risk or strategy…"/><button className={`send ${generating?'stop':''}`} onClick={()=>generating?stop():void send()} disabled={!input.trim()&&!generating}>{generating?<Pause size={16}/>:<ArrowUpRight size={16}/>}</button></div><div className="composer-meta"><span><Zap size={10}/> local WebGPU AI</span><span>{connected?<Wifi size={10}/> : <WifiOff size={10}/>} {connected?'live market feed':'feed offline'}</span><span><ShieldCheck size={10}/> no trading account access</span><span><kbd>Ctrl</kbd>+<kbd>K</kbd> focus</span></div></div></section></main>
 {settingsOpen&&<SettingsModal settings={settings} setSettings={setSettings} webgpu={webgpu} onClose={()=>setSettingsOpen(false)}/>}</div>
}
function Metric({label,value,tone}:{label:string;value:string;tone?:string}){return <div className="metric"><span>{label}</span><strong className={tone||''}>{value}</strong></div>}
function Loader({progress,status}:{progress:number;status:string}){return <div className="loader"><div className="bar"><i style={{width:`${progress}%`}}/></div><span>{status} · {progress}%</span></div>}
function RiskCalc({price}:{price:number}){const [account,setAccount]=useState(2000);const [risk,setRisk]=useState(0.5);const [stop,setStop]=useState(250);const amount=account*risk/100;const size=stop>0?amount/stop:0;return <div className="risk-form"><label><span>Account</span><input type="number" value={account} onChange={e=>setAccount(+e.target.value||0)}/></label><label><span>Risk %</span><input type="number" step="0.1" value={risk} onChange={e=>setRisk(+e.target.value||0)}/></label><label><span>Stop distance</span><input type="number" value={stop} onChange={e=>setStop(+e.target.value||1)}/></label><div className="risk-result"><div><span>Risk amount</span><b>${amount.toFixed(2)}</b></div><div><span>Units @ {fmt(price)}</span><b>{size.toFixed(4)}</b></div></div></div>}
function Chart({candles}:{candles:Candle[]}){const w=900,h=300;const data=candles.slice(-90);if(!data.length)return <div className="chart-empty"><Activity size={20}/><span>Waiting for live candles…</span></div>;const max=Math.max(...data.map(c=>c.high)),min=Math.min(...data.map(c=>c.low));const x=w/Math.max(data.length,1);const y=(v:number)=>20+(max-v)/(max-min||1)*220;return <div className="chart"><svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none">{[0,1,2,3].map(i=><line key={i} x1="0" x2={w} y1={20+i*55} y2={20+i*55} className="grid"/>)}{data.map((c,i)=>{const up=c.close>=c.open;const cx=i*x+x/2;const yo=y(c.open),yc=y(c.close),top=y(c.high),bot=y(c.low);return <g key={c.time} className={up?'up':'down'}><line x1={cx} x2={cx} y1={top} y2={bot}/><rect x={cx-x*.28} y={Math.min(yo,yc)} width={x*.56} height={Math.max(2,Math.abs(yc-yo))}/></g>})}</svg></div>}
function SettingsModal({settings,setSettings,webgpu,onClose}:{settings:SettingsState;setSettings:any;webgpu:boolean;onClose:()=>void}){return <div className="modal"><div className="dialog"><div className="dialog-head"><div><strong>V14 Settings</strong><span>Local day-trading workspace</span></div><button className="icon-btn" onClick={onClose}><X size={15}/></button></div><label><span>Temperature <b>{settings.temperature.toFixed(2)}</b></span><input type="range" min="0" max="1" step="0.05" value={settings.temperature} onChange={e=>setSettings((s:any)=>({...s,temperature:+e.target.value}))}/></label><label><span>Max output tokens <b>{settings.maxTokens}</b></span><input type="range" min="256" max="4096" step="128" value={settings.maxTokens} onChange={e=>setSettings((s:any)=>({...s,maxTokens:+e.target.value}))}/></label><div className="switch-row"><div><strong>Save chats locally</strong><small>Saved only in this browser.</small></div><button className={`switch ${settings.saveChats?'on':''}`} onClick={()=>setSettings((s:any)=>({...s,saveChats:!s.saveChats}))}><i/></button></div><div className="diag"><span><Gauge size={13}/>WebGPU</span><b className={webgpu?'positive':'negative'}>{webgpu?'available':'not available'}</b></div><div className="diag"><span><Wifi size={13}/>Live data</span><b>Binance public WebSocket</b></div><div className="dialog-actions"><button onClick={()=>setSettings((s:any)=>({...s,theme:s.theme==='dark'?'light':'dark'}))}>{settings.theme==='dark'?<Sun size={13}/>:<Moon size={13}/>}Theme</button><button onClick={onClose}>Done</button></div></div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
